import type { Role } from "@/types";

export const TOPIC_MAP: Record<Role, string[]> = {
  frontend: [
    "html-css",
    "javascript-core",
    "react",
    "performance",
    "accessibility",
    "bundlers",
    "typescript",
    "testing-frontend",
  ],
  backend: [
    "api-design",
    "databases",
    "caching",
    "authentication",
    "message-queues",
    "microservices",
    "concurrency",
    "testing-backend",
  ],
  fullstack: [
    "javascript-core",
    "react",
    "api-design",
    "databases",
    "authentication",
    "deployment",
    "typescript",
    "testing-frontend",
  ],
  devops: [
    "ci-cd",
    "containers",
    "kubernetes",
    "cloud",
    "monitoring",
    "infrastructure-as-code",
    "networking",
    "security",
  ],
  "data-engineer": [
    "sql",
    "data-pipelines",
    "spark",
    "data-modeling",
    "streaming",
    "cloud-data",
    "python-data",
    "data-quality",
  ],
  "ml-engineer": [
    "ml-fundamentals",
    "deep-learning",
    "mlops",
    "feature-engineering",
    "model-serving",
    "python-ml",
    "statistics",
    "nlp",
  ],
};

export const TOPIC_DISPLAY: Record<string, string> = {
  "html-css": "HTML & CSS",
  "javascript-core": "JavaScript Core",
  react: "React",
  performance: "Web Performance",
  accessibility: "Accessibility",
  bundlers: "Bundlers & Build Tools",
  typescript: "TypeScript",
  "testing-frontend": "Frontend Testing",
  "api-design": "API Design",
  databases: "Databases",
  caching: "Caching",
  authentication: "Authentication",
  "message-queues": "Message Queues",
  microservices: "Microservices",
  concurrency: "Concurrency",
  "testing-backend": "Backend Testing",
  deployment: "Deployment",
  "ci-cd": "CI/CD",
  containers: "Containers & Docker",
  kubernetes: "Kubernetes",
  cloud: "Cloud Platforms",
  monitoring: "Monitoring & Observability",
  "infrastructure-as-code": "Infrastructure as Code",
  networking: "Networking",
  security: "Security",
  sql: "SQL",
  "data-pipelines": "Data Pipelines",
  spark: "Apache Spark",
  "data-modeling": "Data Modeling",
  streaming: "Stream Processing",
  "cloud-data": "Cloud Data Warehouses",
  "python-data": "Python for Data",
  "data-quality": "Data Quality",
  "ml-fundamentals": "ML Fundamentals",
  "deep-learning": "Deep Learning",
  mlops: "MLOps",
  "feature-engineering": "Feature Engineering",
  "model-serving": "Model Serving",
  "python-ml": "Python for ML",
  statistics: "Statistics",
  nlp: "NLP",
};
